#!/usr/bin/env node
// One-shot: embed the vendored public-domain cover artwork as a JS module so
// it loads identically under dev ES modules and the esbuild single-file build.
//
//   node tools/embed-art.mjs   (regenerates js/data/coverArt.js)
//
// Sources (both public domain):
//   vendor/art/voyager_golden_plaque.svg      — full cover design, PD-US,
//     vectorization VectorVoyager / Wikimedia Commons, after NASA/JPL
//   vendor/art/voyager_cover_explanation.svg  — NASA/JPL annotated diagram,
//     PD-USGov-NASA (rev. Brian Krent, 2015)

import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const plaque = readFileSync(new URL('vendor/art/voyager_golden_plaque.svg', root), 'utf8');
const explanation = readFileSync(new URL('vendor/art/voyager_cover_explanation.svg', root), 'utf8');

const module = `// GENERATED by tools/embed-art.mjs — do not edit by hand.
// Voyager Golden Record cover artwork (public domain, NASA/JPL; plaque
// vectorization VectorVoyager via Wikimedia Commons).

// Full cover design: gold disk fill '#d4af37', 195 white strokes.
const PLAQUE_RAW = ${JSON.stringify(plaque)};

// NASA annotated explanation diagram: black strokes, white fills.
const EXPLANATION_RAW = ${JSON.stringify(explanation)};

// The plaque, restyled: strokes -> \`stroke\`, the gold disk fill -> \`disk\`
// ('none' lets a richer canvas-painted gold show through).
export function plaqueSvg({ stroke = '#3e3220', disk = 'none' } = {}) {
  return PLAQUE_RAW
    .replaceAll('stroke:#ffffff', 'stroke:' + stroke)
    .replaceAll('fill:#d4af37', 'fill:' + disk);
}

// The explanation diagram, restyled for the page's dark theme.
export function explanationSvg({ stroke = '#c9a227', fill = '#0d0a06' } = {}) {
  return EXPLANATION_RAW
    .replaceAll('stroke="#000000"', 'stroke="' + stroke + '"')
    .replaceAll('fill="#FFFFFF"', 'fill="' + fill + '"');
}

// data: URI for canvas rasterization via new Image()
export function svgToDataUri(svg) {
  return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
}
`;

writeFileSync(new URL('js/data/coverArt.js', root), module);
console.log(`js/data/coverArt.js written (${(module.length / 1024).toFixed(0)} KB)`);
